/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Convertidor;

/**
 *
 * @author Aaron Alfonseca
 */
public class InterfazConvertidor extends javax.swing.JFrame {

    public InterfazConvertidor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    boolean km = false;
    boolean mp = false;

    public void kilometros() {
        if (km) {
            slmillas.setValue((int) (float) (this.slkilometros.getValue() * 0.621371));
        }
        numkm.setText(Float.valueOf(this.slkilometros.getValue()) + " km/h");
    }

    public void millas() {
        if (mp) {
            slkilometros.setValue((int) (float) (this.slmillas.getValue() * 1.60934));
        }
        nummill.setText(Float.valueOf(this.slmillas.getValue()) + " mph");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numkm = new javax.swing.JLabel();
        slkilometros = new javax.swing.JSlider();
        nummill = new javax.swing.JLabel();
        slmillas = new javax.swing.JSlider();
        btnsalir = new javax.swing.JButton();
        jlbkilometros = new javax.swing.JLabel();
        jlbmillas = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numkm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        numkm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(numkm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, 40));

        slkilometros.setMaximum(500);
        slkilometros.setValue(0);
        slkilometros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slkilometrosStateChanged(evt);
            }
        });
        slkilometros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slkilometrosMouseEntered(evt);
            }
        });
        getContentPane().add(slkilometros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 264, -1));

        nummill.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nummill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(nummill, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 80, 40));

        slmillas.setMaximum(500);
        slmillas.setValue(0);
        slmillas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slmillasStateChanged(evt);
            }
        });
        slmillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slmillasMouseEntered(evt);
            }
        });
        getContentPane().add(slmillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 264, -1));

        btnsalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 66, -1));

        jlbkilometros.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbkilometros.setText("Kilómetros");
        getContentPane().add(jlbkilometros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jlbmillas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbmillas.setText("Millas");
        getContentPane().add(jlbmillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slkilometrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slkilometrosStateChanged
        kilometros();
    }//GEN-LAST:event_slkilometrosStateChanged

    private void slmillasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slmillasStateChanged
        millas();
    }//GEN-LAST:event_slmillasStateChanged

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void slkilometrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slkilometrosMouseEntered
        km = true;
        mp = false;
    }//GEN-LAST:event_slkilometrosMouseEntered

    private void slmillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slmillasMouseEntered
        km = false;
        mp = true;
    }//GEN-LAST:event_slmillasMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jlbkilometros;
    private javax.swing.JLabel jlbmillas;
    private javax.swing.JLabel numkm;
    private javax.swing.JLabel nummill;
    private javax.swing.JSlider slkilometros;
    private javax.swing.JSlider slmillas;
    // End of variables declaration//GEN-END:variables
}
