/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Convertidor;

/**
 *
 * @author Aaron Alfonseca
 */
public class InterfazConvertidor extends javax.swing.JFrame {

    public InterfazConvertidor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    boolean km = false;
    boolean mp = false;

    public void kilometros() {
        if (km) {
            slmillas.setValue((int) (float) (this.slkilometros.getValue() * 0.621371));
            numkm.setText(Float.valueOf(this.slkilometros.getValue()) + " km/h");
        }
    }

    public void millas() {
        if (mp) {
            slkilometros.setValue((int) (float) (this.slmillas.getValue() * 1.60934));
            nummill.setText(Float.valueOf(this.slmillas.getValue()) + " mph");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numkm = new javax.swing.JLabel();
        slkilometros = new javax.swing.JSlider();
        nummill = new javax.swing.JLabel();
        slmillas = new javax.swing.JSlider();
        btnsalir = new javax.swing.JButton();
        jlbkilometros = new javax.swing.JLabel();
        jlbmillas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numkm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        numkm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        slkilometros.setMaximum(500);
        slkilometros.setValue(0);
        slkilometros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slkilometrosStateChanged(evt);
            }
        });
        slkilometros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slkilometrosMouseEntered(evt);
            }
        });

        nummill.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nummill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        slmillas.setMaximum(500);
        slmillas.setValue(0);
        slmillas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slmillasStateChanged(evt);
            }
        });
        slmillas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                slmillasMouseEntered(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jlbkilometros.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbkilometros.setText("Kilómetros");

        jlbmillas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jlbmillas.setText("Millas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbmillas)
                            .addComponent(jlbkilometros)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(slkilometros, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                .addComponent(slmillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(numkm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nummill, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jlbkilometros)
                .addGap(19, 19, 19)
                .addComponent(slkilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numkm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlbmillas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(slmillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nummill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slkilometrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slkilometrosStateChanged
        kilometros();
    }//GEN-LAST:event_slkilometrosStateChanged

    private void slmillasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slmillasStateChanged
        millas();
    }//GEN-LAST:event_slmillasStateChanged

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void slkilometrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slkilometrosMouseEntered
        km = true;
        mp = false;
    }//GEN-LAST:event_slkilometrosMouseEntered

    private void slmillasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slmillasMouseEntered
        km = false;
        mp = true;
    }//GEN-LAST:event_slmillasMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jlbkilometros;
    private javax.swing.JLabel jlbmillas;
    private javax.swing.JLabel numkm;
    private javax.swing.JLabel nummill;
    private javax.swing.JSlider slkilometros;
    private javax.swing.JSlider slmillas;
    // End of variables declaration//GEN-END:variables
}
